# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Examples' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod 'RxSwift', '~> 4.2.0'
   pod 'RxCocoa', '~> 4.2.0'
   pod 'RxDataSources', '~> 3.0.2'
   pod 'NSObject+Rx', '~> 4.3.0'
   pod 'SnapKit', '~> 4.0.0'
   pod 'ObjectMapper', '~> 3.2.0'
   pod 'Alamofire', '~> 4.7.2'
  # Pods for Examples

end
